version: 0.2

phases:
  install:
    commands:
      - echo "Installing Node.js via nvm..."
      - |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm install 18.18.2
        nvm use 18.18.2
        node -v
        npm ci

  build:
    commands:
      - echo "Building the project..."
      - npm run build
      - cp appspec.yml dist/

artifacts:
  files:
    - '**/*'
  base-directory: dist
